name: eppo
description: Eppo SDK for Dart and Flutter applications
version: 1.0.0
homepage: https://geteppo.com
repository: https://github.com/eppo/eppo-dart
license: MIT

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.3.0
  logging: ^1.1.0
  crypto: ^3.0.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.21.0
  mockito: ^5.3.0
