name: eppo
description: Eppo SDK for Dart
version: 0.1.0-alpha.1
repository: https://github.com/eppo/eppo-dart

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
